### ISSUE TITLE
ScopeMag aplification factor

### ISSUE THREAD

**Issue by spaivaras** [schlae/crt-driver#2]
Hello, I am creating this issue as it seems I can't post a comment on your blog. First thank you for your work, it seems to be a single resource on the web which is easy to follow and explains a lot about custom crt drivers.

I have a question tho regarding amplification of ScopeMag bord. I tried it on some old old 9" crt. It seems to work but i only get a deflection of third of the screen. Preamp stage generates a peek signals of around 11 V . So I guess i need to tweek power amplifiers amplification factor. As I understand R8 (49.9K from opamp output to power amp inverting input) and R11 (1 meg) configures the amplification rate, so basically lowering R8 should pump more amps to the coils? I am not so bright on analog circuits :) so your input would be much valuable. Thank you

**Comment by schlae** [comment]
Yes, you are correct, lower R8 to increase the gain. Be careful that you don't drive too much current, you might overheat the amplifier chip. You will notice a lot of visual distortion before that happens, however.

**Comment by spaivaras** [comment]
Thank you
